### ISSUE TITLE
Better handling of tasks without actions

### ISSUE THREAD

**Issue by bollwyvl** [deathbeds/doitoml#13]
## Elevator Pitch

Allow for tasks with sub-tasks to define `meta`, `task_dep`, without `actions`.

## Motivation

The primary use case is for allowing skipping whole chunks of tasks with `meta`, such as not running formatters in CI:

```toml
# pyproject.toml
[tool.doitoml.tasks.format]
meta = {doitoml={skip="${CI}"}}

[tool.doitoml.tasks.format.black]
# ...

[tool.doitoml.tasks.format.ruff]
# ...
```

## Design Ideas

> TBD
